#! /bin/sh

launch_polybar
xrdb ~/.Xresources	# reload X resources for some reason

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scratchpad sticky=on state=floating hidden=on
st -c scratchpad -e launch_scratchpad &
