require("plug")
require("bindings")
require("general")

require("config.cmp")
require("config.lsp")
require("config.treesitter")
require("config.telescope")
require("config.lualine")
require("config.neorg")
require("config.vimwiki")
